// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aiqkmzotqqkqhnuyleae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpcWttem90cXFrcWhudXlsZWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMTIzNDIsImV4cCI6MjA4NDU4ODM0Mn0.Z5T-F56waIlILKoqDtfHEn-VF4BVCs-yJWi_lqtGRLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});